compress_assets: off
gzip_assets: off

javascripts:
  assets:
    - dependencies/jquery-1.6.1.min.js
    - dependencies/underscore-min.js
    - dependencies/backbone-min.js
    - compiled/namespace.js
    - compiled/lib/*.js    
    - compiled/mvc/*.js
    - compiled/bootstrap.js